apiVersion: apps/v1
kind: Deployment
metadata:
  name: interfaceserver
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: interfaceserver
  template:
    metadata:
      labels:
        app: interfaceserver
    spec:
      containers:
        - name: interfaceserver
          image: gcr.io/hopeful-altar-392410/serverinterface:latest  # Replace with your Docker image details
          ports:
            - containerPort: 8010
