apiVersion: v1
kind: Service
metadata:
  name: interfaceserver
spec:
  selector:
    app: interfaceserver
  ports:
    - port: 8010
      targetPort: 8010
  type: LoadBalancer  # Use NodePort or LoadBalancer depending on your cluster setup
